spring:
  data:
    mongodb:
      uri: mongodb+srv://jaya2000:${MONGODB_PASSWORD}@cluster0.5pptl.mongodb.net/piggymetrics?retryWrites=true&w=majority

server:
  servlet:
    context-path: /uaa
  port: 5000
